# Generated by Django 3.0.5 on 2020-04-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createBy', to='user.RandomUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='distributeUser',
            field=models.ManyToManyField(related_name='distributeUser', to='user.RandomUser'),
        ),
    ]
