# Generated by Django 3.0.3 on 2020-04-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.RandomUserModel'),
        ),
    ]
