# Generated by Django 3.0.3 on 2020-04-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200414_1540'),
        ('post', '0002_post_createby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.RandomUser'),
        ),
    ]
