# Generated by Django 3.0.5 on 2020-04-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200414_1540'),
        ('post', '0003_auto_20200414_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distributeUser',
            field=models.ManyToManyField(related_name='distributeUser', to='user.RandomUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createBy', to='user.RandomUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
