# Generated by Django 3.0.5 on 2020-04-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200414_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('01', 'Normal'), ('02', 'Warning')], default='01', max_length=2)),
                ('is_active', models.BooleanField()),
                ('adminId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Admin')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
