# Generated by Django 3.0.3 on 2020-04-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcementmodel',
            name='type',
            field=models.CharField(choices=[('02', 'Warning'), ('01', 'Normal')], default='01', max_length=2),
        ),
    ]
