# Generated by Django 3.0.5 on 2020-04-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20200419_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='type',
            field=models.CharField(choices=[('01', 'Normal'), ('02', 'Warning')], default='01', max_length=2),
        ),
    ]
