# Generated by Django 3.0.5 on 2020-04-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='randomUser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.RandomUser'),
        ),
        migrations.AddField(
            model_name='chat',
            name='random_user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='random_user1', to='user.RandomUser'),
        ),
        migrations.AddField(
            model_name='chat',
            name='random_user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='random_user2', to='user.RandomUser'),
        ),
    ]
