# Generated by Django 3.0.3 on 2020-04-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200414_1540'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('random_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='random_user1', to='user.RandomUser')),
                ('randomuser2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='random_user2', to='user.RandomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
                ('randomUser1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.RandomUser')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
