# Generated by Django 3.0.3 on 2020-04-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200418_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='randomuser2',
            new_name='random_user2',
        ),
    ]
