# Generated by Django 3.0.5 on 2020-04-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200418_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-time',)},
        ),
    ]
