# Generated by Django 3.0.3 on 2020-04-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200414_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200414_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomUserModel',
        ),
        migrations.AddField(
            model_name='randomuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
