# Generated by Django 3.0.3 on 2020-04-13 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200413_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authen_user',
            name='ban_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banusermodel',
            name='ban_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 17, 14, 19, 925968), null=True),
        ),
    ]
