# Generated by Django 3.0.3 on 2020-04-13 18:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0003_auto_20200413_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banusermodel',
            name='ban_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 18, 6, 51, 195027), null=True),
        ),
    ]
