# Generated by Django 3.0.3 on 2020-04-13 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200413_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banusermodel',
            name='ban_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 18, 9, 51, 853018), null=True),
        ),
    ]
