# Generated by Django 3.0.3 on 2020-04-13 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200413_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banusermodel',
            name='ban_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 18, 10, 3, 458648), null=True),
        ),
    ]
