# Generated by Django 3.0.3 on 2020-04-13 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0008_auto_20200413_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ban_date', models.DateField(default=datetime.datetime(2020, 4, 13, 18, 14, 53, 670546), null=True)),
                ('remark', models.TextField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Admin')),
            ],
        ),
        migrations.DeleteModel(
            name='BanUserModel',
        ),
    ]
