# Generated by Django 3.0.3 on 2020-04-13 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200413_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='ban_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 18, 15, 31, 922785), null=True),
        ),
    ]
