# Generated by Django 3.0.3 on 2020-04-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200424_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentBy',
        ),
    ]
